### ISSUE TITLE
Uncaught exception 'UntrustedIdentityException' in SessionBuilder.php:154 - script crash

### ISSUE THREAD

**Issue by estcap** [WHAnonymous/Chat-API#1260]
I am running the last commit.
My script seems to work for a random period of time and suddenly gives this error in the terminal (running from Putty). It allways fails with just this number of mine which I write from rarely (Scribbled to {PHONENUMBER}  below), but I have recieved and sent images and texts before.

I previously submited this https://github.com/WHAnonymous/Chat-API/issues/1130 which was since fixed with https://github.com/WHAnonymous/Chat-API/pull/1203 . I think this is related but can't seem to find closed issues related to this.

```
rx  <iq from="s.whatsapp.net" type="result" id="2">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ ÇÙªewrtertfg5£îµ»PY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Q)ñÉÓÚdsdfgsdfg¶u?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷ròoíy¦öÿ@!sdfgsdfgOÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id></id>
rx          <value>*iªN8x3íý¿C[vÑ¥çkªCÓ±¿Øuâþ$</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="1">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ ÇÙª3hîäewrtY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Q)ñÉsdfgsdfg&Qý6Rù­öÙ¶u?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷ròoíy¦öÿ@!âsdfgsdfg3E$I$OÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id>Ç</id>
rx          <value>Z.*!Ä;#ÜÆsdfgsdfgÛô0Å-</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="5">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ ÇÙfghsdfhsdhf2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Q)ñsdfgsdfhgdfh?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷ròoíy¦öÿ@sdfhsdfh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id>A</id>
k</value>   <value>bLÍüafdsgdsfgsdfgsdfgB{C;qFÄ«        D
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="4">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ sdrgsdrgdsrgdsrg£îµ»PY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥fdghdfhgdfhfh1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷ròdfghdfhdfhdhE$I$OÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id></id>
rx          <value>øZ©@sthsth¤È~</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="8">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ hdfhdhdfhth£îµ»PY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:dthrthdtrh¶u?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷drthdrthrdthdrthE$I$OÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id>Å</id>
rx          <value>+-ú]ÚsdrthdrthsZOCµu\Éº</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="7">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ Çhrthrthrth|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Q)retherthrthrthÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷rthrhrthrtherhE$I$OÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id>@</id>
rx          <value>ö}aÓî-trhrthrthtyK<N}</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

PuTTYPuTTYPuTTYPuTTYrx  <iq from="s.whatsapp.net" type="result" id="6">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ rgfhrdthdrht£îµ»PY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Qddfhdh?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷d®*r3E$I$OÞXh²¤Ce<fghdfhdh/signature>
rx        </skey>
rx        <key>
rx          <id></id>
rx          <value>:3HOdfhdfhdhwM«©XZçb</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="3">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ rtyrtyrtyerty£îµ»PY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Q)ñÉertyeryRù­öÙ¶u?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷rertrthth®*r3E$I$OÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id>Æ</id>
rx          <value>Ê3kS'Í8´¾F)¹0ÏåÍ   ãåæVJòÐº4s</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="a">
rx    <list>
rx      <user jid="{PHONENUMBER}@s.whatsapp.net">
rx        <registration>q~v</registration>
rx        <type></type>
rx        <identity>ò¬ Çrghrdthdrthµ»PY|2</identity>
rx        <skey>
rx          <id></id>
rx          <value>Y²¥:Q)ñÉdrthdrthdrthÙ¶u?1ÀG±ao</value>
rx          <signature>IPßLI1WùÍ/w 
                                   é,÷rdthtrhdrthdrthE$I$OÞXh²¤Ce</signature>
rx        </skey>
rx        <key>
rx          <id>Ä</id>
rx          <value>ã^drthrth§Â¨í±-gl$ç}
ó9</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

PHP Fatal error:  Uncaught exception 'UntrustedIdentityException' in /usr/local/whatsapp/src/libaxolotl-php/SessionBuilder.php:154
Stack trace:
#0 /usr/local/whatsapp/src/handlers/IqHandler.php(264): SessionBuilder->processPreKeyBundle(Object(PreKeyBundle))
#1 /usr/local/whatsapp/src/whatsprot.class.php(2271): IqHandler->Process()
#2 /usr/local/whatsapp/src/whatsprot.class.php(2004): WhatsProt->processInboundDataNode(Object(ProtocolNode))
#3 /usr/local/whatsapp/src/whatsprot.class.php(302): WhatsProt->processInboundData('\x80\x01\f\x8E1\xE7\xD1\xD0\x0F\xCA\x81\xB4\x0EW\xF9...')
#4 /usr/local/whatsapp/src/whatsprot.class.php(1753): WhatsProt->pollMessage()
#5 /usr/local/whatsapp/src/whatsprot.class.php(406): WhatsProt->waitForServer('a')
#6 /usr/local/whatsapp/src/whatsprot.class.php(2098): WhatsProt->sendGetCipherKeysFromUser('{PHONENUMBER}', true)
#7 /usr/local/whatsapp/src/whatsprot.class.php(2004): WhatsProt->processInboundDataNode(Object(ProtocolNode))
#8 /usr/local/whatsapp/src/whatsprot.class.php(302): WhatsProt->process in /usr/local/whatsapp/src/libaxolotl-php/SessionBuilder.php on line 154```



*UPDATE*
I deleted axolotl DB and seemed to work and recived several messages I had sent, before crashing again with the log:
```PHP Fatal error:  Call to a member function getChainKey() on null in /usr/local/whatsapp/src/libaxolotl-php/state/SessionState.php on line 137```

Running it yet again seems to work fine, at least in the 10 minutes I had it running and tried from several numbers sending recieving pictures and texts. I have yet to test it with the original {PHONENUMBER} that caused trouble.

**Comment by mgp25** [comment]
@estcap issue tracked, will be fixed in next release.

Regards

**Comment by edudesouza** [comment]
Hi there, I got the same error. I have an application witch listen messages in two phone numbers, one of them is a new number never user, the other is my personal number, witch is a very old whatsapp account.
