### ISSUE TITLE
Very very slow

### ISSUE THREAD

**Issue by Derpingson** [WHAnonymous/Chat-API#1278]
When I try to start my whatsapp server, the server is very slow and does +- 5 min to get all the contacts (5) profile pictures, and if I skip that part it takes about 2 or 3 minutes to send a message.

And after a while I get an  'Connection Closed!' exception.
And sometimes this error:
PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /var/www/traffiction/api/assets/whatsapp/whatsprot.class.php on line 2634

Any of you guys know how to fix this?

**Comment by mgp25** [comment]
@Derpingson not API issue, you are doing something wrong.

For further support, post full debug log and full script code

Regards

**Comment by Derpingson** [comment]
```php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="xxxxxxxxx">Þÿ©8b31647482654T¬¡M(Áj9b848aÜ
ÕâÄNt¥1449423391</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>8dþ·83²86IáùH¬ï×oòÉR|Ã</challenge>

tx  <response>:`AÈ9õ!۝8b8bx·39ceã*OÔt989eá-åÁèFÞ</response>

rx  <success t="1449423391" props="4" kind="free" status="active" creation="1426971466" expiration="1458507466">Ú}MZ^íwø»·²}MVê95'</success>

tx  <presence name="Derpingson"></presence>

tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

rx  <presence from="xxxxxxxxx@s.whatsapp.net"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <iq from="xxxxxxxxx@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="error" id="2">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="3" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="3">
rx    <props version="4">
rx      <prop name="audio" value="1"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="e2e_audio" value="0"></prop>
rx      <prop name="e2e_blists" value="0"></prop>
rx      <prop name="e2e_groups" value="1"></prop>
rx      <prop name="e2e_images" value="0"></prop>
rx      <prop name="e2e_video" value="0"></prop>
rx      <prop name="file_max_size" value="64"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="image_max_edge" value="1600"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx      <prop name="max_participants" value="101"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="mspes" value="1"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="plaintext_disabled" value="1"></prop>
rx      <prop name="plaintext_reenable_threshold" value="5"></prop>
rx      <prop name="qr" value="1"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="source" value="1"></prop>
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="wbarchive" value="1"></prop>
rx    </props>
rx  </iq>

tx  <chatstate to="xxxxxxxxx@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <message to="xxxxxxxxx@s.whatsapp.net" type="text" id="r13fP0Q2p8jG1" t="1449423511" notify="Derpinson">
tx    <body>test</body>
tx  </message>

rx  <ack from="xxxxxxxxx@s.whatsapp.net" class="message" id="r13fP0Q2p8jG1" t="1449423511"></ack>

rx  <receipt from="xxxxxxxxx@s.whatsapp.net" id="r13fP0Q2p8jG1" t="1449423512"></receipt>

tx  <ack to="xxxxxxxxx@s.whatsapp.net" class="receipt" id="r13fP0Q2p8jG1" t="1449423512"></ack>

tx  <chatstate to="xxxxxxxxx@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <message to="xxxxxxxxx@s.whatsapp.net" type="text" id="r13fP0Q2p8jG3" t="1449423752" notify="Derpinson">
tx    <body>test 2</body>
tx  </message>

PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /var/www/api/assets/whatsapp/whatsprot.class.php on line 2634
rx  <stream:error>
rx    <ack id="r13fP0Q2p8jG1"></ack>
rx  </stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/api/assets/whatsapp/whatsprot.class.php:291
Stack trace:
#0 /var/www/api/assets/whatsapp/whatsprot.class.php(1753): WhatsProt->pollMessage()
#1 /var/www/api/assets/whatsapp/whatsprot.class.php(2731): WhatsProt->waitForServer('r13fP0Q2p8jG3')
#2 /var/www/api/server/helpers/WhatsApp.php(229): WhatsProt->sendMessageNode('xxxxxxxxx', Object(ProtocolNode), NULL)
#3 /var/www/api/server/helpers/Functions.php(64): Server\Helpers\WhatsApp->sendMessage('xxxxxxxxx', 'test 2', '2661')
#4 /var/www/api/server/helpers/Functions.php(38): Server\Helpers\Functions->sendMessage(Object(API\Models\Outgoing))
#5 /var/www/api/server/helpers/Runner.php(57): Server\Helpers\Functions->callFunction(Object(API\Models\Outgoing))
#6 /var/www/api/server/helpers/WhatsApp.php(88): Server\Helpers\Runner->run()
#7 /var/www/api/server/tasks/MainTask in /var/www/api/assets/whatsapp/whatsprot.class.php on line 291
root@server:/var/www/api/server#
```

**Comment by Derpingson** [comment]
I changed my PHP version back to 5.5 and now it's working normally again.
