### ISSUE TITLE
Group creation problem

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#1311]
I am trying to use the groups functions.
Every time I get system shutdown and then my user is blocked.
This perfectly was working for me.
I have the latest code from today.
Can someone advise ---> Thx
This is what I do and get:
```
<?php
header('Content-Type: text/html; charset=utf-8');
require 'src/whatsprot.class.php';

$groupName='test123';
$userPhone='31654.......';
$password='xxxxxxxxxx';
$userIdentity='0';
$nickname='test';
$debug='1';
$members = array('31654.......');

		$wa = new WhatsProt($userPhone, $userIdentity,$nickname,$debug);
		$wa->connect();
		$wa->loginWithPassword($password);
		$gid= $wa->sendGroupsChatCreate($groupName, $members);
		echo $gid;

$wa->disconnect();


tx  stream:features>
tx    readreceipts>/readreceipts>
tx    groups_v2>/groups_v2>
tx    privacy>/privacy>
tx    presence>/presence>
tx  /stream:features>

tx  auth mechanism="WAUTH-2" user="31xxxxxxx">/auth>

rx  start from="s.whatsapp.net">/start>

rx  stream:features>/stream:features>

rx  challenge>F¦v$?¦¦¦¦¦]¦¦$¦]¦/challenge>

tx  response>l¦¦=¦i¦¦¦¦¦¦¦p%¦¦¦z¦l4¦¦?¦q¦¦
¦¦/response>

rx  success t="1450516493" props="4" kind="free" status="active" creation="1450516447" expiration="1482052447">VY¦¦hA¦¦H¦?L¦/success>

tx  presence name="0">/presence>

tx  iq xmlns="w:g2" id="1" type="set" to="g.us">
tx    create subject="alialliun12">
tx      participant jid="31xxxxxxx@s.whatsapp.net">/participant>
tx    /create>
tx  /iq>

rx  ib from="s.whatsapp.net">
rx    dirty type="groups" timestamp="1450516493">/dirty>
rx  /ib>

tx  iq id="2" type="set" to="s.whatsapp.net" xmlns="urn:xmpp:whatsapp:dirty">
tx    clean type="groups">/clean>
tx  /iq>

rx  ib from="s.whatsapp.net">
rx    offline count="0">/offline>
rx  /ib>

rx  presence from="31xxxxxxx@s.whatsapp.net">/presence>

rx  iq from="s.whatsapp.net" type="result" id="2">/iq>

rx  stream:error>
rx    system-shutdown>/system-shutdown>
rx  /stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/generic/services/whatsappNew/src/whatsprot.class.php:280
Stack trace:
#0 /home/generic/services/whatsappNew/src/whatsprot.class.php(1740): WhatsProt->pollMessage()
#1 /home/generic/services/whatsappNew/src/whatsprot.class.php(1085): WhatsProt->waitForServer('1')
#2 /home/generic/services/whatsappNew/test_create_group.php(16): WhatsProt->sendGroupsChatCreate('test123', Array)
#3 {main}
```

**Comment by 0xTryCatch** [comment]
Maybe your IP is blocked. Can you try from another server?

**Comment by mgp25** [comment]
@yanelev you are using a wrong constructor, do you have latest API code? And don't disconnect too soon, add a few `pollMessage` before disconnecting

**Comment by yanelev** [comment]
Thank you for the reply. I have the latest one from today...if its the latest ...
Surprisingly when I try it from a different server  like 0xTryCatch suggested it works.
mgp25, does it make sense. My sendMessage on another code works perfectly on the suspected blocked IP and no problem there. Does it make sense?

I will try with the poolMessage too, but I doubt if this is the issue.

Thx

**Comment by mgp25** [comment]
@yanelev try to make it like a human would do... anyway, yes, your server maybe its blocked and thats why from another works

Regards
