### ISSUE TITLE
Problem to Login

### ISSUE THREAD

**Issue by sologestion** [WHAnonymous/Chat-API#1439]
Hello, i have trouble to login.

Try
1) Update api source.
2) Getting password 4 times.

**Debug**

```xml
tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <stream:features></stream:features>

tx  <auth user="549************" mechanism="WAUTH-2">Çúç╒5493624178277[╕âσ╘&#é6²«∞←ƒ▐↑π↓<⌡1452436708</auth>


Fatal error: Uncaught exception 'LoginFailureException' in C:\wa_borras_r4\src\Login.php:54
Stack trace:
#0 C:\wa_borras_r4\src\whatsprot.class.php(286): Login->doLogin()
#1 C:\wa_borras_r4\enviar_y_recibir_borras.php(29): WhatsProt->loginWithPassword
('U2vxHluA/RBS1a2...')
#2 {main}
  thrown in C:\wa_borras_r4\src\Login.php on line 54
```

**This is the Log**
```xml
2016-01-10 11:42:41] [INFO]: Connected to WA server
```

**The Code that i using**

```php
$nickname_01 = "Sistema Borras";
$username_01 = "549**********";
$password_01 = "U2v**********c=";
$debug = True;
$log = True;

$w = new WhatsProt($username_01, $nickname_01, $debug, $log);
$w->eventManager()->bind('onGetSyncResult', 'onSyncResult');
$w->eventManager()->bind("onGetMessage", "GetMessage");
$w->eventManager()->bind("onGetImage", "onGetImage");
$w->eventManager()->bind("onGetVideo", "onGetVideo");		
$w->connect(); 
$w->sendGetPrivacyBlockedList();
$w->loginWithPassword($password_01); 
$w->sendGetClientConfig(); 
$w->sendGetServerProperties();
$w->sendGetGroups();
$w->sendGetBroadcastLists(); 
```

**This Registration**
```xml
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 549************


Type sms or voice: voice
Array
(
    [cc] => 54
    [in] => **********
    [lg] => es
    [lc] => AR
    [id] => ♀jñ`Γ_iµü.▲⌠°√½↑╡τ£ß
    [token] => +8Fs6B**********IQFA=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 6618
    [rchash] => 577d742631cc7**********************0314d724aaee37672208920fad1d98

    [anhash] => 601ab3c5bf370f****************d44
    [extexist] => 1
    [extstate] => 1
    [mcc] => 722
    [mnc] => 000
    [sim_mcc] => 722
    [sim_mnc] => 000
    [method] => voice
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => voice
    [retry_after] => 1805
)


Enter the received code: 4******

Your username is: 549************
Your password is: U2vx*********KRc=
```

It only happens with this line in particular.

Thanks in advance.

Gabriel

**Comment by mgp25** [comment]
Sorry, you are not metting WhatsApp EULA and Chat API conditions, which clearly says: **You will NOT use this API with commercial use. Only for personal usage**
