### ISSUE TITLE
Encrypt message and Error in resetAccount

### ISSUE THREAD

**Issue by borjapu** [WHAnonymous/Chat-API#1449]
Hello, i had problems reciving messages. because i cant read it.
look: 
```php
[data:ProtocolNode:private] => 3!9z*§(ú«Â¸Ôqß¢q@–„I«yGû!ˆO!¯žsD–a4ÆOÑó0îúcO„£†Aú¿¥õ&ð
"B3
!ZãZ\ÛIìµÇ¥¶ËƒÁWT•ë>ïµ¥ç"®öÈê<^Sg#D™(ðà¨jjYù(ÒÏÖß0žÀ¹
                        )
                )
```
I have looking for a solution , and i think i have to use resetAcount.php
but it doesnt work. 
it shows me this error. 
```console
PHP Warning:  array_fill(): Number of elements must be positive in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 349
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:279
PHP  12. array_fill() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:349
PHP Warning:  array_map(): Argument #2 should be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:279
PHP  12. array_map() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Warning:  implode(): Argument must be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:279
PHP  12. implode() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Warning:  array_fill(): Number of elements must be positive in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 349
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:281
PHP  12. array_fill() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:349
PHP Warning:  array_map(): Argument #2 should be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:281
PHP  12. array_map() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Warning:  implode(): Argument must be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:281
PHP  12. implode() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:299
Stack trace:
#0 /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php(1784): WhatsProt->pollMessage()
#1 /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php(1034): WhatsProt->waitForServer('03')
#2 /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php(33): WhatsProt->sendRemoveAccount()
#3 {main}
  thrown in /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php on line 299

```
I dont know why i have these error, can anyone help me?, thanks in advance

**Comment by mgp25** [comment]
@borjapu update to latest API code, install dependencies and extensions. Remove `axolotl.db` if you have one.

Start the script again and it should work fine.

Regards
