### ISSUE TITLE
Encrypted vcard problem

### ISSUE THREAD

**Issue by larwa** [WHAnonymous/Chat-API#1463]
Hi guys,

because of another problem, I updated chat-api to the current master a few hours ago.

Now my client throws an error, as soon as I receive an encrypted vcard.
It's actually just a warning, but can't be right anyway.

Encryption of text messages works, not sure about media messages, as the scripts aborts here atm.

BTW: Thanks for all the awesome work!

Greets, Lars

Exception:
```
Warning: file_get_contents(): Filename cannot be empty
```

Debug output:
```
rx  <message from="55139967XXXX@s.whatsapp.net" type="media" id="E52EBB78F32000EBA27" offline="1" t="1452626141" notify="blabla">
rx    <media type="vcard" encoding="text">
rx      <vcard name="some name">424547494e3a56434152440a56455253494f4e3a332e300a4e3a666c616d65723b746574656c3b3b3b0a464e3a746574656c20666c616d65720a6974656d312e54454c3a2b353520343420393838352d373438310a6974656d312e582d41424c6162656c3a43656c2e0a454e443a5643415244</vcard>
rx    </media>
rx  </message>
```

Stack trace:
```
#1 /xxx/vendor/whatsapp/chat-api/src/handlers/MessageHandler.php(54): file_get_contents('')
#2 /xxx/vendor/whatsapp/chat-api/src/whatsprot.class.php(2375): MessageHandler->Process()
#3 /xxx/vendor/whatsapp/chat-api/src/whatsprot.class.php(2083): WhatsProt->processInboundDataNode(Object(ProtocolNode))
#4 /xxx/vendor/whatsapp/chat-api/src/whatsprot.class.php(311): WhatsProt->processInboundData('\x80\x00\xCD\f\x964\xECQU\x13\xA85uT\x81...')
#5 /xxx/vendor/whatsapp/chat-api/src/whatsprot.class.php(1802): WhatsProt->pollMessage()
#6 /xxx/vendor/whatsapp/chat-api/src/whatsprot.class.php(416): WhatsProt->waitForServer('0c')
#7 /xxx/vendor/whatsapp/chat-api/src/handlers/MessageHandler.php(340): WhatsProt->sendGetCipherKeysFromUser('55139967XXXX')
#8 /xxx/vendor/whatsapp/chat-api/src/handlers/MessageHandler.php(263): MessageHandler->processEncryptedNode(Object(ProtocolNode))
#9 /xxx/vendor/whatsapp/chat-api/src/handlers/MessageHandler.php(38): MessageHandler->processMessageNode(Object(ProtocolNode))
```

**Comment by mgp25** [comment]
@larwa its not encrypted, is just hex encoded, this is the output:

```
BEGIN:VCARD
VERSION:3.0
N:flamer;tetel;;;
FN:tetel flamer
item1.TEL:+55 44 9885-7481
item1.X-ABLabel:Cel.
END:VCARD
```

Use this event:
`onGetvCard( $mynumber, $from, $id, $type, $time, $name, $vcardname, $vcard )`

Regards

**Comment by larwa** [comment]
Ok, thanks, so the call of file_get_contents call with an empty string parameter comes from another event. I'll do some debugging if it occurs again. Temporary, I fixed it by suppressing the warning (@).
