### ISSUE TITLE
tests doesn't work 

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#1491]
Hi,

It seems that the file whatsapp.php doesn't work with the last update.
The old version works fine.
```xml
[] Logging in as 'sligo' (316xxxxx)
  <stream:features>
    <readreceipts></readreceipts>
    <groups_v2></groups_v2>
   <privacy></privacy>
    <presence></presence>
  </stream:features>

  <auth mechanism="WAUTH-2" user="316xxxxxx"></auth>

  <start from="s.whatsapp.net"></start>

 <stream:features></stream:features>

  <challenge>j9>¦¦N2/"
¦¦¦¦¦</challenge>

  <response>¦¦G¦¦dq¦¦i¦x¦>¦¦E¦"7q¦¦Cq¦_</response>

  <failure>
    <not-authorized></not-authorized>
  </failure>
```

```
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /vendor/whatsapp/chat-api/src/whatsprot.class.php:2270
Stack trace:
#0 /vendor/whatsapp/chat-api/src/whatsprot.class.php(551): WhatsProt->doLogin()
#1 /vendor/whatsapp/chat-api/tests/whatsapp1.php(44): WhatsProt->loginWithPassword('NOxxxxxxxxx...')
#2 {main}

  thrown in /vendor/whatsapp/chat-api/src/whatsprot.class.php on line 2270
```

**Comment by mgp25** [comment]
1. It works perfectly
2. You havent quoted the debug properly (i have done it for you)
3. You haven't tested if the number is blocked with the provided scripts in `/examples` like `blockChecker.php`
4. You haven't tryied to register it again

Do i have to continue?
