### ISSUE TITLE
socket_connect(): unable to connect [110]: Connection timed out

### ISSUE THREAD

**Issue by DarkAllMan** [WHAnonymous/Chat-API#868]
Sinds today I'm getting these errors:

```
PHP Warning:  socket_connect(): unable to connect [110]: Connection timed out in /var/www/vhosts/domain/domain/Chat-API-master/src/whatsprot.class.php on line 426 PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/vhosts/domain/domain/Chat-API-master/src/whatsprot.class.php:565
Stack trace:
#0 /var/www/vhosts/domain/domain/Chat-API-master/src/whatsprot.class.php(2258): WhatsProt->pollMessage()
#1 /var/www/vhosts/domain/domain/Chat-API-master/src/whatsprot.class.php(551): WhatsProt->doLogin()
#2 /var/www/vhosts/domain/domain/send_whatsapp.php(19): WhatsProt->loginWithPassword('gEkjRuLdhTmy1Ns...')
#3 {main}
  thrown in /var/www/vhosts/domain/domain/Chat-API-master/src/whatsprot.class.php on line 565
```

**Comment by mgp25** [comment]
@DarkAllMan you have an outdated code, update it
