### ISSUE TITLE
Encrypted message

### ISSUE THREAD

**Issue by zilverdael** [WHAnonymous/Chat-API#893]
When doing a $w->pollMessage(); the message body recieved seems encrypted.
How do i get it decrypted??

rx  <message from="XxXxXyYy@s.whatsapp.net" id="XxXxXyYy.--295" offline="0" type="text" t="1438088718" notify="XxXxXyYy">
rx    <enc v="1" type="pkmsg">3B!î ®ÚAŠÅ-Ë/˜ânÇ’ÿ¨î›ÿxÇ*7~èrh!_¤®Z U:½C/•g‘ÎL}·Q¿éÚü9g¨!ŒCy""R3 !ŒÍÀ«¢ÆPÞOPý6CMn5”î{yˆeËí–c" 0Ð›ôAÓù‰C´'¶Dü›¥BùMîçÎ&k4Ð¾¯›‡’xšû(¦¬Ï0</enc>
rx  </message>

**Comment by 0xTryCatch** [comment]
Please check existing issues first, this questions has been asked several times before.

Answer: https://github.com/WHAnonymous/Chat-API/issues/858#issuecomment-122224842

**Comment by borjapu** [comment]
Hello i'm having problems with the encrption, i try to execute the tool resetAccount.php but i doesn't work. 
it throws me this message:
``` console
PHP Warning:  array_fill(): Number of elements must be positive in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 349
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:279
PHP  12. array_fill() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:349
PHP Warning:  array_map(): Argument #2 should be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:279
PHP  12. array_map() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Warning:  implode(): Argument must be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363

PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:281
PHP  12. array_fill() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:349
PHP Warning:  array_map(): Argument #2 should be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:281
PHP  12. array_map() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Warning:  implode(): Argument must be an array in /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php on line 363
PHP Stack trace:
PHP   1. {main}() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:0
PHP   2. WhatsProt->loginWithPassword() /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php:24
PHP   3. Login->doLogin() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:286
PHP   4. WhatsProt->sendAvailableForChat() /home/whatsapp2/public_html/Chat-API-master/src/Login.php:58
PHP   5. WhatsProt->sendNode() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:1511
PHP   6. BinTreeNodeWriter->write() /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:2900
PHP   7. BinTreeNodeWriter->writeInternal() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:52
PHP   8. BinTreeNodeWriter->writeAttributes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:101
PHP   9. BinTreeNodeWriter->writeString() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:326
PHP  10. BinTreeNodeWriter->writeBytes() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:314
PHP  11. BinTreeNodeWriter->tryPackAndWriteHeader() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:281
PHP  12. implode() /home/whatsapp2/public_html/Chat-API-master/src/BinTreeNodeWriter.php:363
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:299
Stack trace:
#0 /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php(1784): WhatsProt->pollMessage()
#1 /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php(1034): WhatsProt->waitForServer('03')
#2 /home/whatsapp2/public_html/Chat-API-master/examples/resetAccount.php(33): WhatsProt->sendRemoveAccount()
#3 {main}
  thrown in /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php on line 299
```
