### ISSUE TITLE
Could not get Authentication code from google

### ISSUE THREAD

**Issue by shvburade** [WHAnonymous/Chat-API#957]
how should i get the authentication code from google
i understood the whole code but why i am unable to get Authentication code from google

i visited to :https://www.google.com/accounts/ClientLogin
there i get a message like "https://developers.google.com/accounts/docs/AuthForInstalledApps"
which api you have used for getting contacts it is different then google api?

i getting error as 

`
Uncaught exception 'Exception' with message 'Could not get Authentication code from google' in C:\Users\Shiva\Documents\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Chat-API-master\examples\shiva_t4.php:94 Stack trace: #0 C:\Users\Shiva\Documents\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Chat-API-master\examples\shiva_t4.php(52): GoogleContacts->getAuthString('SHIVA') #1 C:\Users\Shiva\Documents\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Chat-API-master\examples\shiva_t4.php(36): GoogleContacts->getGoogleContacts('SHIVA') #2 C:\Users\Shiva\Documents\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Chat-API-master\examples\shiva_t4.php(176): GoogleContacts->getContacts(Array, 'SHIVA') #3 {main} thrown in C:\Users\Shiva\Documents\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Chat-API-master\examples\shiva_t4.php on line 94
`

my whole code is

```php
<?php

require '../src/whatsprot.class.php';

$config['SHIVA'] = array(
    'fromNumber' => '91mynumber',
    'nick' => "dharmesh",
    'waPassword' => "mypassword",
    'email' => 'shivaburade20@gmail.com',
    'emailPassword' => 'myspassword'
);

interface Contacts
{
    public function getContacts(array $config, $user);
}

class GoogleContacts implements Contacts
{
    private $config;
    private $curl;
    private $auth;
    private $headers;

    public function __construct()
    {
        $this->curl = curl_init();
    }

    public function getContacts(array $config, $user)
    {
        if (!array_key_exists($user, $config)) {
            throw new Exception("No Credentials for the user requested are available.");
        } else {
            $this->config = $config;
            $contacts = $this->getGoogleContacts($user);
        }
        if (is_array($contacts)) {
            print_r($contacts);
        }

        return false;
    }

    private function getGoogleContacts($user)
    {
        if (!isset($this->config[$user]['email'])) {
            throw new Exception("Email address for $user was not supplied or set.");
        }

        try {
            $auth = $this->getAuthString($user);
            $this->setHeaders($auth);
            $groupid = $this->getGoogleGroupId('System Group: My Contacts');
            $contacts = $this->retreiveContacts($groupid);
        } catch (Exception $e) {
            throw $e;
        }

        return $contacts;
    }

    private function getAuthString($user)
    {
        // Construct an HTTP POST request
        $clientlogin_url = "https://www.google.com/accounts/ClientLogin";
        $clientlogin_post = array(
            "accountType" => "HOSTED_OR_GOOGLE",
            "Email" => $this->config[$user]['email'],
            "Passwd" => $this->config[$user]['emailPassword'],
            "service" => "cp",
            "source" => "whatsapp"
        );

        // Set some options (some for SHTTP)
        curl_setopt($this->curl, CURLOPT_URL, $clientlogin_url);
        curl_setopt($this->curl, CURLOPT_POST, true);
        curl_setopt($this->curl, CURLOPT_POSTFIELDS, $clientlogin_post);
        curl_setopt($this->curl, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
        curl_setopt($this->curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, 1);

        // Execute
        $authresponse = curl_exec($this->curl);

        // Get the Auth string and save it
        $matches = null;
        $res = preg_match("/Auth=([a-z0-9_-]+)/i", $authresponse, $matches);
        if ($res == 1) {
            $this->auth = $matches[1];

            return $matches[1];
        }
        throw new Exception('Could not get Authentication code from google');
    }

    private function setHeaders($auth)
    {
        $this->headers = array(
            "Authorization: GoogleLogin auth=" . $auth,
            "GData-Version: 2.0",
        );
    }

    private function getHeaders()
    {
        return $this->headers;
    }

    private function getGoogleGroupId($groupname)
    {
        // Connect to Google and get a list of all contact groups.
        curl_setopt($this->curl, CURLOPT_URL, "https://www.google.com/m8/feeds/groups/default/full");
        curl_setopt($this->curl, CURLOPT_HTTPHEADER, $this->getHeaders());
        curl_setopt($this->curl, CURLOPT_POST, false);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, true);

        $groupresponse = curl_exec($this->curl);

        //Load XML response
        $atom = simplexml_load_string($groupresponse);

        //Find the group id for the main contact group.
        foreach ($atom->entry as $entry) {
            if (stristr($entry->title, $groupname) !== false) {
                $contactgroup = $entry->id;
            }
        }

        if (isset($contactgroup)) {
            return $contactgroup;
        } else {
            return false;
        }
    }

    private function retreiveContacts($groupid)
    {
        curl_setopt($this->curl, CURLOPT_URL, "https://www.google.com/m8/feeds/contacts/default/full?max-results=2000&group=$groupid");
        curl_setopt($this->curl, CURLOPT_HTTPHEADER, $this->getHeaders());
        curl_setopt($this->curl, CURLOPT_POST, false);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, true);

        $contactsresponse = curl_exec($this->curl);
        curl_close($this->curl);

        //Load XML response
        $contactsxml = simplexml_load_string($contactsresponse);
        $data = array();
        foreach ($contactsxml->entry as $entry) {
            $name = $entry->title;
            $gd = $entry->children('http://schemas.google.com/g/2005');
            foreach ($gd->phoneNumber as $p) {
                if ($p->attributes()->rel == "http://schemas.google.com/g/2005#mobile") {
                    $n = trim(preg_replace("/[\D+]*/", "", $p));
                    if (substr((string) $n, 0, 1) !== '0' && strlen($n) > 10) {
                        $data[] = array('name' => "$name ($n)", 'id' => $n);
                    }
                }
            }
        }
        usort($data, array($this, 'sortByName'));

        return($data);
    }

    public function sortByName($a, $b)
    {
        return strcasecmp($a['name'], $b['name']);
    }

}


$google = new GoogleContacts();
$googleContacts = $google->getContacts($config, 'SHIVA');
?>
```

**Comment by WHAnonymous** [comment]
@shvburade not API related, sorry

**Comment by shvburade** [comment]
can you tell me which api is being used to get contacts from google?
